routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('access')->name('main');

Route::get('/news', 'NewsController@index')->name('news');
Route::post('/set-enter-pin', 'NewsController@enterPin')->name('set.enter.pin');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->middleware('access')->name('login');
Route::post('login', 'Auth\LoginController@login')->middleware('access');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->middleware('access')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->middleware('access')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->middleware('access')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->middleware('access');

Route::group(['prefix' => '/workers', 'middleware' => ['auth', 'access']], function() {
    Route::get('/', 'User\WorkerController@index')->name('worker.index');
    Route::get('/create', 'User\WorkerController@create')->name('worker.create');
    Route::post('/store', 'User\WorkerController@store')->name('worker.store');
    Route::get('/edit/{worker}', 'User\WorkerController@edit')->name('worker.edit');
    Route::get('/view/{worker}', 'User\WorkerController@view')->name('worker.view');
    Route::put('/update/{worker}', 'User\WorkerController@update')->name('worker.update');
    Route::delete('/delete/{worker}', 'User\WorkerController@delete')->name('worker.delete');
});

Route::group(['prefix' => '/shops', 'middleware' => ['auth', 'access']], function() {
    Route::get('/', 'Shop\ShopController@index')->name('shop.index');
    Route::get('/create', 'Shop\ShopController@create')->name('shop.create');
    Route::post('/store', 'Shop\ShopController@store')->name('shop.store');
    Route::get('/edit/{shop}', 'Shop\ShopController@edit')->name('shop.edit');
    Route::get('/view/{shop}', 'Shop\ShopController@view')->name('shop.view');
    Route::put('/update/{shop}', 'Shop\ShopController@update')->name('shop.update');
    Route::delete('/delete/{shop}', 'Shop\ShopController@delete')->name('shop.delete');
});

Route::group(['prefix' => '/individual-clients', 'middleware' => ['auth', 'access']], function() {
    Route::get('/', 'Client\IndividualClientController@index')->name('individual.client.index');
    Route::get('/create', 'Client\IndividualClientController@create')->name('individual.client.create');
    Route::post('/store', 'Client\IndividualClientController@store')->name('individual.client.store');
    Route::get('/edit/{client}', 'Client\IndividualClientController@edit')->name('individual.client.edit');
    Route::get('/view/{client}', 'Client\IndividualClientController@view')->name('individual.client.view');
    Route::put('/update/{client}', 'Client\IndividualClientController@update')->name('individual.client.update');
    Route::delete('/delete/{client}', 'Client\IndividualClientController@delete')->name('individual.client.delete');
});

Route::group(['prefix' => '/legal-clients', 'middleware' => ['auth', 'access']], function() {
    Route::get('/', 'Client\LegalClientController@index')->name('legal.client.index');
    Route::get('/create', 'Client\LegalClientController@create')->name('legal.client.create');
    Route::post('/store', 'Client\LegalClientController@store')->name('legal.client.store');
    Route::get('/edit/{client}', 'Client\LegalClientController@edit')->name('legal.client.edit');
    Route::get('/view/{client}', 'Client\LegalClientController@view')->name('legal.client.view');
    Route::put('/update/{client}', 'Client\LegalClientController@update')->name('legal.client.update');
    Route::delete('/delete/{client}', 'Client\LegalClientController@delete')->name('legal.client.delete');
});

Route::group(['prefix' => '/ajax', 'middleware' => ['auth', 'access']], function() {
    Route::get('/get-client-contact-full-name-by-select', 'Client\ClientController@getClientContactFullName')->name('ajax.get.client.by.select');

});

Route::group(['prefix' => '/factory', 'middleware' => ['auth', 'access']], function() {
    Route::get('/', 'FactoryController@index')->name('factory.index');
    Route::get('/create', 'FactoryController@create')->name('factory.create');
    Route::post('/store', 'FactoryController@store')->name('factory.store');
    Route::get('/edit/{factory}', 'FactoryController@edit')->name('factory.edit');
    Route::get('/view/{factory}', 'FactoryController@view')->name('factory.view');
    Route::put('/update/{factory}', 'FactoryController@update')->name('factory.update');
    Route::delete('/delete/{factory}', 'FactoryController@delete')->name('factory.delete');
});

Route::group(['prefix' => '/documents', 'middleware' => ['auth', 'access']], function() {

    // documents
    Route::get('/', 'Document\DocumentController@index')->name('document.index');
    Route::get('/table', 'Document\DocumentController@table')->name('document.table.index');
    Route::get('/create', 'Document\DocumentController@create')->name('document.create');
    Route::post('/store', 'Document\DocumentController@store')->name('document.store');
    Route::get('/view/{document}', 'Document\DocumentController@view')->name('document.view');
    Route::get('/edit/{document}', 'Document\DocumentController@edit')->name('document.edit');
    Route::put('/update/{document}', 'Document\DocumentController@update')->name('document.update');
    Route::delete('/delete/{document}', 'Document\DocumentController@delete')->name('document.delete');
    Route::post('/calculation', 'Document\DocumentController@calculationSum')->name('document.calculation');
    Route::post('/calculation-surcharge/{document}', 'Document\DocumentController@calculationSumSurcharge')->name('document.calculation.surcharge');
    Route::post('/save-additional-field/{document}', 'Document\DocumentController@saveAdditionalField')->name('document.save.additionals');
    Route::post('/new-payment/{document}', 'Document\DocumentController@createNewDocumentPayment')->name('document.new.payment');
    Route::post('/calculation-finish-date', 'Document\DocumentController@calculationDateFinish')->name('document.calculation.date-finish');
    Route::get('/get-attach-template-form/{document}', 'Document\DocumentController@getAttachDocumentTemplateFrom')->name('document.get.attach.template.form');
    Route::post('/attach-template/{document}', 'Document\DocumentController@attachDocumentTemplate')->name('document.attach.template');
    Route::get('/get-attach-product-form/{document}', 'ProductController@getAttachProductForm')->name('document.get.attach.product.form');
    Route::post('/attach-product/{document}', 'ProductController@attachProductToDocument')->name('document.attach.product');
    Route::get('/get-edit-product-form/{product}', 'ProductController@getEditProductForm')->name('document.get.edit.product.form');
    Route::post('/update-product/{product}', 'ProductController@updateProduct')->name('document.update.product');
    Route::post('/delete-product/{product}', 'ProductController@delete')->name('document.product.delete');

    // document templates
    Route::get('/templates', 'Document\TemplateController@index')->name('document.template.index');
    Route::get('/templates/show-with-document/{document}/{template}', 'Document\TemplateController@showTemplateWithDocument')->name('document.template.with.document');
    Route::delete('/templates/delete-relation-with-document/{document}/{template}', 'Document\TemplateController@deleteTemplateRelationWithDocument')->name('document.template.delete.relation.with.document');
    Route::get('/templates/create', 'Document\TemplateController@create')->name('document.template.create');
    Route::post('/templates/store', 'Document\TemplateController@store')->name('document.template.store');
    Route::get('/templates/edit/{template}', 'Document\TemplateController@edit')->name('document.template.edit');
    Route::get('/templates/view/{template}', 'Document\TemplateController@view')->name('document.template.view');
    Route::put('/templates/update/{template}', 'Document\TemplateController@update')->name('document.template.update');
    Route::delete('/templates/delete/{template}', 'Document\TemplateController@delete')->name('document.template.delete');
    Route::get('/templates/to-pdf/{document}/{template}', 'Document\TemplateController@toPdf')->name('document.template.with.document.topdf');
    Route::get('/templates/to-doc/{document}/{template}', 'Document\TemplateController@toDoc')->name('document.template.with.document.todoc');

    Route::get('/service-account/get-add-form/{document}', 'Document\ServiceAccountController@getAddServiceAccountForm')->name('document.service-account.form');
    Route::get('/service-account/change-type-payment/{document}', 'Document\ServiceAccountController@changeTypePayment')->name('document.service-account.change-type-payment');
    Route::post('/service-account/attach-service-account/{document}', 'Document\ServiceAccountController@attachServiceAccountToDocument')->name('document.service-account.attach');
    Route::get('/service-account/view/{serviceAccount}', 'Document\ServiceAccountController@view')->name('document.service-account.view');
    Route::get('/service-account/pdf/{serviceAccount}', 'Document\ServiceAccountController@pdf')->name('document.service-account.pdf');

app/Models/Client/LegalClient.php
<?php

namespace App\Models\Client;

use Illuminate\Database\Eloquent\Model;

/**
 * Model for table `legal_clients`
 */
class LegalClient extends Model
{
    /**
     * {@inheritdoc}
     *
     * @access protected
     * @var array $fillable
     */
    protected $fillable = [
        'full_name',
        'short_name',
        'address',
        'email',
        'phone',
        'ogrn',
        'inn',
        'kpp',
        'bank',
        'bik',
        'checking_account',
        'general_director_surname',
        'general_director_name',
        'general_director_lastname',
        'general_director_phone',
        'general_director_email',
        'personal_surname',
        'personal_name',
        'personal_lastname',
        'personal_phone',
        'personal_email',
        'shipping_address',
    ];

    /**
     * Get legal client full name + director full name.
     *
     * @return array
     */
    public function getPersonalFullNameAttribute()
    {
        return $this->full_name . '/' . $this->general_director_surname . ' ' . $this->general_director_name . ' ' . $this->general_director_lastname;
    }

    /**
     * Get legal client contact full name.
     *
     * @return array
     */
    public function getContactFullNameAttribute()
    {
        return $this->personal_surname . ' ' . $this->personal_name . ' ' . $this->personal_lastname;
    }
}

app/Http/Controllers/Client/ClientController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\ClientService;

/**
 * Client controller.
 */
class ClientController extends Controller
{
    /**
     * client service.
     *
     * @var \App\Services\ClientService $clientService
     * @access private
     */
    private $clientService;

    /**
     * Controller constructor.
     *
     * @param \App\Services\ClientService $workerService Client service
     * @return void
     */
    public function __construct(ClientService $clientService)
    {
        $this->clientService = $clientService;
    }

    /**
     * Display page with all individual clients.
     *
     * @param \Illuminate\Http\Request $request Request
     * @return \Illuminate\Support\Facades\View
     */
    public function getClientContactFullName(Request $request)
    {
        return response()->json([
            'contact_full_name' => $this->clientService->getClientContactFullNameBySelect($request->client),
        ]);
    }
}

app/Http/Controllers/Client/IndividualClientController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\ClientService;
use App\Http\Requests\IndividualClientCreateRequest;
use App\Http\Requests\IndividualClientUpdateRequest;
use App\Models\Client\IndividualClient;
use Illuminate\Support\Facades\Auth;

/**
 * Individual client controller.
 */
class IndividualClientController extends Controller
{
    /**
     * client service.
     *
     * @var \App\Services\ClientService $clientService
     * @access private
     */
    private $clientService;

    /**
     * Controller constructor.
     *
     * @param \App\Services\ClientService $workerService Client service
     * @return void
     */
    public function __construct (ClientService $clientService)
    {
        $this->clientService = $clientService;
    }

    /**
     * Display page with all individual clients.
     *
     * @param \Illuminate\Http\Request $request Request
     * @return \Illuminate\Support\Facades\View
     */
    public function index(Request $request)
    {
        if (!Auth::user()->isCanViewIndividualClients()) {
            $this->accessDanied();
        }

        return view('client.individual-client.index', [
            'clients' => $this->clientService->individualClientsWithPaginate(),
        ]);
    }

    /**
     * Display page with form create new individual client.
     *
     * @param \Illuminate\Http\Request $request Request
     * @return \Illuminate\Support\Facades\View
     */
    public function create(Request $request)
    {
        if (!Auth::user()->isCanCreateIndividualClient()) {
            $this->accessDanied();
        }

        return view('client.individual-client.create');
    }

    /**
     * Create new individual client.
     *
     * @param \App\Http\Requests\IndividualClientCreateRequest $request Request for individual client
     * @return \Illuminate\Support\Facades\Redirect
     */
    public function store(IndividualClientCreateRequest $request)
    {
        if (!Auth::user()->isCanCreateIndividualClient()) {
            $this->accessDanied();
        }

        $client = $this->clientService->createNewIndividualClient($request->all());

        if ($request->ajax()) {
            return response()->json([
                'status' => true,
                'key' => 'i-' . $client->id,
                'value' => $client->fullName,
                'contactFullName' => $client->contactFullName,
            ]);
        }

        return redirect(route('individual.client.index'));
    }

    /**
     * Display page with client information.
     *
     * @param \App\Models\Client\IndividualClient $client Model individual client
     * @param \Illuminate\Http\Request $request Request
     * @return \Illuminate\Support\Facades\View
     */
    public function view(IndividualClient $client, Request $request)
    {
        if (!Auth::user()->isCanViewIndividualClient()) {
            $this->accessDanied();
        }

        return view('client.individual-client.view', compact('client'));
    }

    /**
     * Display page with form update individual client.
     *
     * @param \App\Models\Client\IndividualClient $client Model individual client
     * @param \Illuminate\Http\Request $request Request
     * @return \Illuminate\Support\Facades\View
     */
    public function edit(IndividualClient $client, Request $request)
    {
        if (!Auth::user()->isCanEditIndividualClient()) {
            $this->accessDanied();
        }

        return view('client.individual-client.update', compact('client'));
    }

    /**
     * Update individual client.
     *
     * @param \App\Models\Client\IndividualClient $client Model individual client
     * @param \App\Http\Requests\IndividualClientUpdateRequest $request Request for update individual client
     * @return \Illuminate\Support\Facades\Redirect
     */
    public function update(IndividualClient $client, IndividualClientUpdateRequest $request)
    {
        if (!Auth::user()->isCanEditIndividualClient()) {
            $this->accessDanied();
        }

        $this->clientService->updateIndividualClient($client, $request->all());

        return redirect(route('individual.client.index'));
    }

    /**
     * Delete individual client.
     *
     * @param \App\Models\Client\IndividualClient $client Model individual client
     * @param \Illuminate\Http\Request $request Request
     * @return \Illuminate\Support\Facades\Redirect
     */
    public function delete(IndividualClient $client, Request $request)
    {
        if (!Auth::user()->isCanDeleteIndividualClient()) {
            $this->accessDanied();
        }

        $client->delete();

        return redirect(route('individual.client.index'));
    }
}

resources/views/client/legal-client/create.blade.php
@extends('layouts.bootstrap')

@section('breadcrumbs')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{ route('legal.client.index') }}">Клиенты: юридические лица</a></li>
            <li class="breadcrumb-item active" aria-current="page">Добавление клиента</li>
        </ol>
    </nav>

@stop
@section('content')

    @include('client.legal-client.form_create', ['showButtons' => true])

@stop

resources/views/client/legal-client/index.blade.php
@extends('layouts.bootstrap')

@section('breadcrumbs')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Клиенты: юридические лица</li>
        </ol>
    </nav>

@stop
@section('content')

    <div class="row">
          <div class="col-lg-12">

                <?php if (Auth::user()->isCanCreateLegalClient()) : ?>

                    <a class="btn btn-success" href="{{ route('legal.client.create') }}">Добавить клиента</a>

                <?php endif; ?>

                <br><br>
                <table class="table">
                      <thead>
                            <tr>
                                  <th>Название полное</th>
                                  <th>Фамилия контактного лица</th>
                                  <th>Имя контактного лица</th>
                                  <th>Отчество контактного лица</th>
                                  <th>Операции</th>
                            </tr>
                      </thead>
                      <tbody>

                          @foreach ($clients as $client)

                              <tr>
                                  <td>
                                      {{ $client->full_name }}
                                  </td>
                                  <td>
                                      {{ $client->personal_surname }}
                                  </td>
                                  <td>
                                      {{ $client->personal_name }}
                                  </td>
                                  <td>
                                      {{ $client->personal_lastname }}
                                  </td>
                                  <td>

                                      <?php if (Auth::user()->isCanEditLegalClient()) : ?>

                                          <a href="{{ route('legal.client.edit', ['client' => $client]) }}"><i class="fa fa-edit fa-2x"></i></a>

                                      <?php endif; ?>
                                      <?php if (Auth::user()->isCanViewLegalClient()) : ?>

                                          <a href="{{ route('legal.client.view', ['client' => $client]) }}"><i class="fa fa-eye fa-2x"></i></a>

                                      <?php endif; ?>
                                      <?php if (Auth::user()->isCanDeleteLegalClient()) : ?>

                                          <form class="delete-form" method="post" action="{{ route('legal.client.delete', ['client' => $client]) }}" style="display: inline">
                                              {{ csrf_field() }}
                                              {{ method_field('DELETE') }}

                                              <button style="color: #337ab7; border: none; background: none"><i class="fa fa-trash fa-2x"></i></button>
                                          </form>

                                      <?php endif; ?>

                                  </td>
                              </tr>

                          @endforeach

                      </tbody>
                </table>

                {{ $clients->links() }}
          </div>
    </div>

@stop

resources/views/client/legal-client/view.blade.php
@extends('layouts.bootstrap')

@section('breadcrumbs')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{ route('legal.client.index') }}">Клиенты: юридические лица</a></li>
            <li class="breadcrumb-item active" aria-current="page">Просмотр клиента</li>
        </ol>
    </nav>

@stop
@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <table style="width: 100%">
                        <tr>
                            <td>
                                <h4>Информация об клиенте</h4>
                            </td>

                            <?php if (Auth::user()->isCanEditLegalClient()) : ?>

                                <td style="text-align: right"><a class="btn btn-warning" style="font-size: 14px" href="{{ route('legal.client.edit', ['client' => $client]) }}">Редактировать</a></td>

                            <?php endif; ?>

                        </tr>
                    </table>
                </div>
                <div class="panel-body">
                    <div class="box box-info">
                        <div class="box-body">
                            <div class="col-lg-3">
                                <div  align="center">
                                    <img alt="User Pic" src="/images/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive">
                                </div>
                                <br>
                                <!-- /input-group -->
                            </div>
                            <div class="col-lg-3">
                                <h4 style="color:#00b1b1;">{{ $client->personal_full_name }}</h4>
                            </div>
                            <div class="col-lg-6">
                                <table class="table">
                                      <tr>
                                          <td>Наименование полное:</td>
                                          <td>{{ $client->full_name }}</td>
                                      </tr>
                                      <tr>
                                          <td>Наименование короткое:</td>
                                          <td>{{ $client->short_name }}</td>
                                      </tr>
                                      <tr>
                                          <td>Юр. адрес:</td>
                                          <td>{{ $client->address }}</td>
                                      </tr>
                                      <tr>
                                          <td>Телефон:</td>
                                          <td>{{ $client->phone }}</td>
                                      </tr>
                                      <tr>
                                          <td>Email:</td>
                                          <td>{{ $client->email }}</td>
                                      </tr>
                                      <tr>
                                          <td>ОГРН:</td>
                                          <td>{{ $client->ogrn }}</td>
                                      </tr>
                                      <tr>
                                          <td>ИНН:</td>
                                          <td>{{ $client->inn }}</td>
                                      </tr>
                                      <tr>
                                          <td>КПП:</td>
                                          <td>{{ $client->kpp }}</td>
                                      </tr>
                                      <tr>
                                          <td>Банк:</td>
                                          <td>{{ $client->bank }}</td>
                                      </tr>
                                      <tr>
                                          <td>БИК:</td>
                                          <td>{{ $client->bik }}</td>
                                      </tr>
                                      <tr>
                                          <td>р/c:</td>
                                          <td>{{ $client->checking_account }}</td>
                                      </tr>
                                      <tr>
                                          <td>Фамилия генерального директора:</td>
                                          <td>{{ $client->general_director_surname }}</td>
                                      </tr>
                                      <tr>
                                          <td>Имя генерального директора:</td>
                                          <td>{{ $client->general_director_name }}</td>
                                      </tr>
                                      <tr>
                                          <td>Отчество генерального директора:</td>
                                          <td>{{ $client->general_director_lastname }}</td>
                                      </tr>
                                      <tr>
                                          <td>Email генерального директора:</td>
                                          <td>{{ $client->general_director_email }}</td>
                                      </tr>
                                      <tr>
                                          <td>Телефон генерального директора:</td>
                                          <td>{{ $client->general_director_phone }}</td>
                                      </tr>
                                      <tr>
                                          <td>Фамилия контактного лица:</td>
                                          <td>{{ $client->personal_surname }}</td>
                                      </tr>
                                      <tr>
                                          <td>Имя контактного лица:</td>
                                          <td>{{ $client->personal_name }}</td>
                                      </tr>
                                      <tr>
                                          <td>Отчество контактного лица:</td>
                                          <td>{{ $client->personal_lastname }}</td>
                                      </tr>
                                      <tr>
                                          <td>Email контактного лица:</td>
                                          <td>{{ $client->personal_email }}</td>
                                      </tr>
                                      <tr>
                                          <td>Телефон контактного лица:</td>
                                          <td>{{ $client->personal_phone }}</td>
                                      </tr>
                                      <tr>
                                          <td>Адрес доставки:</td>
                                          <td>{{ $client->shipping_address }}</td>
                                      </tr>
                                </table>
                            </div>
                        </div>
                        <!-- /.box -->
                    </div>
                </div>
            </div>
        </div>
    </div>

@stop