routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('access')->name('main');

Route::get('/news', 'NewsController@index')->name('news');
Route::post('/set-enter-pin', 'NewsController@enterPin')->name('set.enter.pin');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->middleware('access')->name('login');
Route::post('login', 'Auth\LoginController@login')->middleware('access');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->middleware('access')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->middleware('access')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->middleware('access')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->middleware('access');

Route::group(['prefix' => '/workers', 'middleware' => ['auth', 'access']], function() {
    Route::get('/', 'User\WorkerController@index')->name('worker.index');
    Route::get('/create', 'User\WorkerController@create')->name('worker.create');
    Route::post('/store', 'User\WorkerController@store')->name('worker.store');
    Route::get('/edit/{worker}', 'User\WorkerController@edit')->name('worker.edit');
    Route::get('/view/{worker}', 'User\WorkerController@view')->name('worker.view');
    Route::put('/update/{worker}', 'User\WorkerController@update')->name('worker.update');
    Route::delete('/delete/{worker}', 'User\WorkerController@delete')->name('worker.delete');
});

Route::group(['prefix' => '/shops', 'middleware' => ['auth', 'access']], function() {
    Route::get('/', 'Shop\ShopController@index')->name('shop.index');
    Route::get('/create', 'Shop\ShopController@create')->name('shop.create');
    Route::post('/store', 'Shop\ShopController@store')->name('shop.store');
    Route::get('/edit/{shop}', 'Shop\ShopController@edit')->name('shop.edit');
    Route::get('/view/{shop}', 'Shop\ShopController@view')->name('shop.view');
    Route::put('/update/{shop}', 'Shop\ShopController@update')->name('shop.update');
    Route::delete('/delete/{shop}', 'Shop\ShopController@delete')->name('shop.delete');
});

Route::group(['prefix' => '/individual-clients', 'middleware' => ['auth', 'access']], function() {
    Route::get('/', 'Client\IndividualClientController@index')->name('individual.client.index');
    Route::get('/create', 'Client\IndividualClientController@create')->name('individual.client.create');
    Route::post('/store', 'Client\IndividualClientController@store')->name('individual.client.store');
    Route::get('/edit/{client}', 'Client\IndividualClientController@edit')->name('individual.client.edit');
    Route::get('/view/{client}', 'Client\IndividualClientController@view')->name('individual.client.view');
    Route::put('/update/{client}', 'Client\IndividualClientController@update')->name('individual.client.update');
    Route::delete('/delete/{client}', 'Client\IndividualClientController@delete')->name('individual.client.delete');
});

Route::group(['prefix' => '/legal-clients', 'middleware' => ['auth', 'access']], function() {
    Route::get('/', 'Client\LegalClientController@index')->name('legal.client.index');
    Route::get('/create', 'Client\LegalClientController@create')->name('legal.client.create');
    Route::post('/store', 'Client\LegalClientController@store')->name('legal.client.store');
    Route::get('/edit/{client}', 'Client\LegalClientController@edit')->name('legal.client.edit');
    Route::get('/view/{client}', 'Client\LegalClientController@view')->name('legal.client.view');
    Route::put('/update/{client}', 'Client\LegalClientController@update')->name('legal.client.update');
    Route::delete('/delete/{client}', 'Client\LegalClientController@delete')->name('legal.client.delete');
});

Route::group(['prefix' => '/ajax', 'middleware' => ['auth', 'access']], function() {
    Route::get('/get-client-contact-full-name-by-select', 'Client\ClientController@getClientContactFullName')->name('ajax.get.client.by.select');

});

Route::group(['prefix' => '/factory', 'middleware' => ['auth', 'access']], function() {
    Route::get('/', 'FactoryController@index')->name('factory.index');
    Route::get('/create', 'FactoryController@create')->name('factory.create');
    Route::post('/store', 'FactoryController@store')->name('factory.store');
    Route::get('/edit/{factory}', 'FactoryController@edit')->name('factory.edit');
    Route::get('/view/{factory}', 'FactoryController@view')->name('factory.view');
    Route::put('/update/{factory}', 'FactoryController@update')->name('factory.update');
    Route::delete('/delete/{factory}', 'FactoryController@delete')->name('factory.delete');
});

Route::group(['prefix' => '/documents', 'middleware' => ['auth', 'access']], function() {

    // documents
    Route::get('/', 'Document\DocumentController@index')->name('document.index');
    Route::get('/table', 'Document\DocumentController@table')->name('document.table.index');
    Route::get('/create', 'Document\DocumentController@create')->name('document.create');
    Route::post('/store', 'Document\DocumentController@store')->name('document.store');
    Route::get('/view/{document}', 'Document\DocumentController@view')->name('document.view');
    Route::get('/edit/{document}', 'Document\DocumentController@edit')->name('document.edit');
    Route::put('/update/{document}', 'Document\DocumentController@update')->name('document.update');
    Route::delete('/delete/{document}', 'Document\DocumentController@delete')->name('document.delete');
    Route::post('/calculation', 'Document\DocumentController@calculationSum')->name('document.calculation');
    Route::post('/calculation-surcharge/{document}', 'Document\DocumentController@calculationSumSurcharge')->name('document.calculation.surcharge');
    Route::post('/save-additional-field/{document}', 'Document\DocumentController@saveAdditionalField')->name('document.save.additionals');
    Route::post('/new-payment/{document}', 'Document\DocumentController@createNewDocumentPayment')->name('document.new.payment');
    Route::post('/calculation-finish-date', 'Document\DocumentController@calculationDateFinish')->name('document.calculation.date-finish');
    Route::get('/get-attach-template-form/{document}', 'Document\DocumentController@getAttachDocumentTemplateFrom')->name('document.get.attach.template.form');
    Route::post('/attach-template/{document}', 'Document\DocumentController@attachDocumentTemplate')->name('document.attach.template');
    Route::get('/get-attach-product-form/{document}', 'ProductController@getAttachProductForm')->name('document.get.attach.product.form');
    Route::post('/attach-product/{document}', 'ProductController@attachProductToDocument')->name('document.attach.product');
    Route::get('/get-edit-product-form/{product}', 'ProductController@getEditProductForm')->name('document.get.edit.product.form');
    Route::post('/update-product/{product}', 'ProductController@updateProduct')->name('document.update.product');
    Route::post('/delete-product/{product}', 'ProductController@delete')->name('document.product.delete');

    // document templates
    Route::get('/templates', 'Document\TemplateController@index')->name('document.template.index');
    Route::get('/templates/show-with-document/{document}/{template}', 'Document\TemplateController@showTemplateWithDocument')->name('document.template.with.document');
    Route::delete('/templates/delete-relation-with-document/{document}/{template}', 'Document\TemplateController@deleteTemplateRelationWithDocument')->name('document.template.delete.relation.with.document');
    Route::get('/templates/create', 'Document\TemplateController@create')->name('document.template.create');
    Route::post('/templates/store', 'Document\TemplateController@store')->name('document.template.store');
    Route::get('/templates/edit/{template}', 'Document\TemplateController@edit')->name('document.template.edit');
    Route::get('/templates/view/{template}', 'Document\TemplateController@view')->name('document.template.view');
    Route::put('/templates/update/{template}', 'Document\TemplateController@update')->name('document.template.update');
    Route::delete('/templates/delete/{template}', 'Document\TemplateController@delete')->name('document.template.delete');
    Route::get('/templates/to-pdf/{document}/{template}', 'Document\TemplateController@toPdf')->name('document.template.with.document.topdf');
    Route::get('/templates/to-doc/{document}/{template}', 'Document\TemplateController@toDoc')->name('document.template.with.document.todoc');

    Route::get('/service-account/get-add-form/{document}', 'Document\ServiceAccountController@getAddServiceAccountForm')->name('document.service-account.form');
    Route::get('/service-account/change-type-payment/{document}', 'Document\ServiceAccountController@changeTypePayment')->name('document.service-account.change-type-payment');
    Route::post('/service-account/attach-service-account/{document}', 'Document\ServiceAccountController@attachServiceAccountToDocument')->name('document.service-account.attach');
    Route::get('/service-account/view/{serviceAccount}', 'Document\ServiceAccountController@view')->name('document.service-account.view');
    Route::get('/service-account/pdf/{serviceAccount}', 'Document\ServiceAccountController@pdf')->name('document.service-account.pdf');

app/Models/Shop/Shop.php
<?php

namespace App\Models\Shop;

use Illuminate\Database\Eloquent\Model;
use App\Models\User\Role;
use App\Models\Shop\ShopUserLeader;

/**
 * Model class for table `shops`.
 */
class Shop extends Model
{
    /**
     * {@inheritdoc}
     *
     * @access protected
     * @var array $fillable
     */
    protected $fillable = [
        'full_name',
        'short_name',
        'address',
        'phone',
        'ogrn',
        'inn',
        'kpp',
        'bank',
        'bik',
        'checking_account',
        'default',
    ];

    /**
     * Get general director for shop.
     *
     * @return null|\App\Models\UserWorker
     */
    public function getGeneralDirectorAttribute()
    {
        $roleGeneralDirector = Role::director()->first();

        $workers = $this->getWorkersByRoleId($roleGeneralDirector->id);

        if (isset($workers[ 0 ])) {
            return $workers[ 0 ];
        }

        return null;
    }

    /**
     * Get worker for this shop with role shop director.
     *
     * @return null|\App\Models\UserWorker
     */
    public function getShopDirectorAttribute()
    {
        $roleShopDirector = Role::shopDirector()->first();

        $workers = $this->getWorkersByRoleId($roleShopDirector->id);

        if (isset($workers[ 0 ])) {
            return $workers[ 0 ];
        }

        return null;
    }

    /**
     * Get workers for this shop with role deputy shop director.
     *
     * @return null|\App\Models\UserWorker[]
     */
    public function getShopDeputyDirectorsAttribute()
    {
        $roleShopDeputyDirector = Role::shopDeputyDirector()->first();

        $workers = $this->getWorkersByRoleId($roleShopDeputyDirector->id);

        if (!empty($workers)) {
            return $workers;
        }

        return null;
    }

    /**
     * Get list workers by role.
     *
     * @param int $roleId Role id.
     * @access private
     * @return
     */
    private function getWorkersByRoleId($roleId)
    {
       return ShopUserLeader::where([
            ['role_id', '=', $roleId],
            ['shop_id', '=', $this->id]
        ])
        ->with('worker')
        ->get()
        ->pluck('worker');
    }
}

app/Models/Shop/ShopUserLeader.php
<?php

namespace App\Models\Shop;

use Illuminate\Database\Eloquent\Model;

/**
 * Model class for table `shop_user_leaders`.
 */
class ShopUserLeader extends Model
{
    /**
     * Relation with table workers.
     *
     * @return
     */
    public function worker()
    {
        return $this->belongsTo('App\Models\User\Worker');
    }
}

app/Http/Controllers/Shop/ShopController.php
<?php

namespace App\Http\Controllers\Shop;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Shop\Shop;
use App\Http\Requests\ShopRequest;
use App\Models\User\Worker;
use App\Services\ShopService;
use Illuminate\Support\Facades\Auth;

/**
 * Shop controller.
 */
class ShopController extends Controller
{
    /**
     * Shop service.
     *
     * @var \App\Services\WorkerService $shopService
     * @access private
     */
    private $shopService;

    /**
     * Controller constructor.
     *
     * @param \App\Services\ShopService $shopService Shop service
     * @return void
     */
    public function __construct(ShopService $shopService)
    {
        $this->shopService = $shopService;
    }

    /**
     * Display page shops.
     *
     * @param \Illuminate\Http\Request $request Request
     * @return \Illuminate\Support\Facades\View
     */
    public function index(Request $request)
    {
        if (!Auth::user()->isCanViewShops()) {
            $this->accessDanied();
        }

        return view('shop.shop.index', [
            'shops' => $this->shopService->paginate(),
        ]);
    }

    /**
     * Display page with shop form for create new shop.
     *
     * @param \Illuminate\Http\Request $request Request
     * @return \Illuminate\Support\Facades\View
     */
    public function create(Request $request)
    {
        if (!Auth::user()->isCanCreateShop()) {
            $this->accessDanied();
        }

        $listGeneralDirectors = Worker::generalDirectors();
        $listShopDirectors = Worker::shopDirectors();
        $listDeputyShopDirectors = Worker::deputyShopDirectors();

        return view('shop.shop.create', compact('listGeneralDirectors', 'listShopDirectors', 'listDeputyShopDirectors'));
    }

    /**
     * Store new shop.
     *
     * @param \App\Http\Requests\ShopRequest $request Shop request
     * @return \Illuminate\Support\Facades\Redirect
     */
    public function store(ShopRequest $request)
    {
        if (!Auth::user()->isCanCreateShop()) {
            $this->accessDanied();
        }

        $this->shopService->createNewShop($request->all());

        return redirect()->route('shop.index');
    }

    /**
     * Display page with shop information.
     *
     * @param \Illuminate\Http\Request $request Request
     * @param \App\Models\Shop\Shop $shop Shop model
     * @return \Illuminate\Support\Facades\View
     */
    public function view(Request $request, Shop $shop)
    {
        if (!Auth::user()->isCanViewShop()) {
            $this->accessDanied();
        }

        return view('shop.shop.view', compact('shop'));
    }

    /**
     * Display page with shop form for edit shop information.
     *
     * @param \Illuminate\Http\Request $request Request
     * @param \App\Models\Shop\Shop $shop Shop model
     * @return \Illuminate\Support\Facades\View
     */
    public function edit(Request $request, Shop $shop)
    {
        if (!Auth::user()->isCanEditShop()) {
            $this->accessDanied();
        }

        $listGeneralDirectors = Worker::generalDirectors();
        $listShopDirectors = Worker::shopDirectors();
        $listDeputyShopDirectors = Worker::deputyShopDirectors();

        $shopDeputyDirectorIds = $this->shopService->getShopDeputyDirectorIds($shop);
        $shopGeneralDirectorId = $this->shopService->getShopGeneralDirectorId($shop);
        $shopDirectorId = $this->shopService->getShopDirectorId($shop);

        return view('shop.shop.edit', [
            'listGeneralDirectors' => $listGeneralDirectors,
            'listShopDirectors' => $listShopDirectors,
            'listDeputyShopDirectors' => $listDeputyShopDirectors,
            'shop' => $shop,
            'shopGeneralDirectorId' => $shopGeneralDirectorId,
            'shopDirectorId' => $shopDirectorId,
            'shopDeputyDirectorIds' => $shopDeputyDirectorIds,
        ]);
    }

    /**
     * Update shop information.
     *
     * @param \App\Http\Requests\ShopRequest $request Shop request
     * @param \App\Models\Shop\Shop $shop Shop model
     * @return \Illuminate\Support\Facades\Redirect
     */
    public function update(ShopRequest $request, Shop $shop)
    {
        if (!Auth::user()->isCanEditShop()) {
            $this->accessDanied();
        }

        $this->shopService->updateShop($shop, $request->all());

        return redirect()->route('shop.index');
    }

    /**
     * Delete shop.
     *
     * @param \Illuminate\Http\Request $request Request
     * @param \App\Models\Shop\Shop $shop Shop model
     * @return \Illuminate\Support\Facades\Redirect
     */
    public function delete(Request $request, Shop $shop)
    {
        if (!Auth::user()->isCanDeleteShop()) {
            $this->accessDanied();
        }

        $shop->delete();

        return redirect(route('shop.index'));
    }
}

resources/views/shop/shop/index.blade.php
@extends('layouts.bootstrap')

@section('breadcrumbs')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Список магазинов</li>
        </ol>
    </nav>

@stop

@section('content')

    <div class="row">
          <div class="col-lg-12">

                <?php if (Auth::user()->isCanCreateShop()) : ?>

                    <a class="btn btn-success" href="{{ route('shop.create') }}">Добавить магазин</a>

                <?php endif; ?>
                <br><br>
                <table class="table">
                      <thead>
                            <tr>
                                  <th>Полное название</th>
                                  <th>Адрес</th>
                                  <th>Директор магазина</th>
                                  <th>Операции</th>
                            </tr>
                      </thead>
                      <tbody>

                          @foreach ($shops as $shop)

                              <tr>
                                  <td>
                                      {{ $shop->full_name }}
                                  </td>
                                  <td>
                                      {{ $shop->address }}
                                  </td>
                                  <td>{{ (!is_null($shop->general_director)) ? $shop->general_director->full_name : '' }}</td>
                                  <td>
                                      <?php if (Auth::user()->isCanEditShop()) : ?>

                                          <a href="{{ route('shop.edit', ['shop' => $shop]) }}"><i class="fa fa-edit fa-2x"></i></a>

                                      <?php endif; ?>
                                      <?php if (Auth::user()->isCanViewShop()) : ?>

                                          <a href="{{ route('shop.view', ['shop' => $shop]) }}"><i class="fa fa-eye fa-2x"></i></a>

                                      <?php endif; ?>
                                      <?php if (Auth::user()->isCanDeleteShop()) : ?>

                                          <form class="delete-form" method="post" action="{{ route('shop.delete', ['shop' => $shop]) }}" style="display: inline">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}

                                                <button style="color: #337ab7; border: none; background: none"><i class="fa fa-trash fa-2x"></i></button>
                                          </form>

                                      <?php endif; ?>
                                  </td>
                              </tr>

                          @endforeach

                      </tbody>
                </table>

                {{ $shops->links() }}
          </div>
    </div>

@stop

resources/views/shop/shop/view.blade.php
@extends('layouts.bootstrap')

@section('breadcrumbs')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{ route('shop.index') }}">Список магазинов</a></li>
            <li class="breadcrumb-item active" aria-current="page">Просмотр магазина</li>
        </ol>
    </nav>

@stop
@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <table style="width: 100%">
                        <tr>
                            <td>
                                <h4>Информация об магазине</h4>
                            </td>

                            <?php if (Auth::user()->isCanEditShop()) : ?>

                                <td style="text-align: right"><a class="btn btn-warning" style="font-size: 14px" href="{{ route('shop.edit', ['shop' => $shop]) }}">Редактировать</a></td>

                            <?php endif; ?>

                        </tr>
                    </table>
                </div>
                <div class="panel-body">
                    <div class="box box-info">
                        <div class="box-body">
                            <div class="col-lg-3">
                                <div  align="center">
                                    <img alt="User Pic" src="/images/Store_icon.png" id="profile-image1" class="img-responsive">
                                </div>
                                <br>
                                <!-- /input-group -->
                            </div>
                            <div class="col-lg-3">
                                <div>
                                    <h3 style="color:#00b1b1;">Генеральный директор</h3>
                                    <span>
                                        <p>{{ (!is_null($shop->general_director)) ? $shop->general_director->full_name : '' }}</p>
                                    </span>
                                </div>
                                <div>
                                    <h4 style="color:#00b1b1;">Директор магазина</h4>
                                    <span>
                                        <p>{{ (!is_null($shop->shop_director)) ? $shop->shop_director->full_name : '' }}</p>
                                    </span>
                                </div>
                                <div>
                                    <h5 style="color:#00b1b1;">Заместители директора магазина</h5>
                                    <span>

                                        @foreach ($shop->shop_deputy_directors as $shopDeputyDirector )

                                            <p>{{ $shopDeputyDirector->full_name }}</p>

                                        @endforeach

                                    </span>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <table class="table">
                                      <tr>
                                          <td>Наименование полное:</td>
                                          <td>{{ $shop->full_name }}</td>
                                      </tr>
                                      <tr>
                                          <td>Наименование короткое:</td>
                                          <td>{{ $shop->short_name }}</td>
                                      </tr>
                                      <tr>
                                          <td>Юр. адрес:</td>
                                          <td>{{ $shop->address }}</td>
                                      </tr>
                                      <tr>
                                          <td>Телефон:</td>
                                          <td>{{ $shop->phone }}</td>
                                      </tr>
                                      <tr>
                                          <td>ОГРН:</td>
                                          <td>{{ $shop->ogrn }}</td>
                                      </tr>
                                      <tr>
                                          <td>ИНН:</td>
                                          <td>{{ $shop->inn }}</td>
                                      </tr>
                                      <tr>
                                          <td>КПП:</td>
                                          <td>{{ $shop->kpp }}</td>
                                      </tr>
                                      <tr>
                                          <td>Банк:</td>
                                          <td>{{ $shop->bank }}</td>
                                      </tr>
                                      <tr>
                                          <td>БИК:</td>
                                          <td>{{ $shop->bik }}</td>
                                      </tr>
                                      <tr>
                                          <td>р/с:</td>
                                          <td>{{ $shop->checking_account }}</td>
                                      </tr>
                                </table>
                            </div>
                        </div>
                        <!-- /.box -->
                    </div>
                </div>
            </div>
        </div>
    </div>

@stop